In [1]:
import pandas as pd
import numpy as np


In [66]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
train_purchases = pd.read_csv("datasets/train_purchases.csv")
train_sessions = pd.read_csv("datasets/train_sessions.csv")
item_features = pd.read_csv("datasets/item_features.csv")
candidate_items = pd.read_csv("datasets/candidate_items.csv")

In [12]:
test_leaderboard = pd.read_csv("datasets/test_leaderboard_sessions.csv")

In [13]:
test_leaderboard.head()

session_id  item_id                     date
0          26    19185  2021-06-16 09:53:54.158
1         200    17089  2021-06-25 12:23:40.811
2         200    17089  2021-06-25 12:24:36.631
3         200     8060  2021-06-25 12:24:41.677
4         200     4758  2021-06-25 12:24:50.692

In [3]:
train_purchases.head()

session_id  item_id                     date
0           3    15085  2020-12-18 21:26:47.986
1          13    18626  2020-03-13 19:36:15.507
2          18    24911  2020-08-26 19:20:32.049
3          19    12534   2020-11-02 17:16:45.92
4          24    13226  2020-02-26 18:27:44.114

session_id  item_id                     date
126753      565440     9655  2020-12-12 06:18:40.836
132194      590009     9655  2020-11-22 18:16:20.948
152638      679929     9655  2020-12-24 19:28:49.403
174217      776357     9655  2020-11-27 12:51:15.099
209747      934553     9655  2020-11-19 09:29:49.214
237733     1058683     9655  2020-12-25 21:58:09.887
395813     1758515     9655  2020-11-21 12:45:17.299
413667     1838092     9655  2021-04-13 12:38:59.819
475820     2113475     9655  2020-11-25 13:30:13.393
497520     2209244     9655  2020-12-26 16:49:42.245
645759     2866783     9655  2020-12-19 21:10:38.921
709738     3152057     9655  2020-11-29 12:22:59.848
724535     3216654     9655  2020-11-29 16:12:33.097
779636     3461663     9655   2021-01-12 19:52:49.37
974117     4325305     9655  2020-12-09 21:27:07.518

In [4]:
train_sessions.head()

session_id  item_id                     date
0           3     9655  2020-12-18 21:25:00.373
1           3     9655  2020-12-18 21:19:48.093
2          13    15654  2020-03-13 19:35:27.136
3          18    18316  2020-08-26 19:18:30.833
4          18     2507  2020-08-26 19:16:31.211

In [9]:
print("Category number : ",len(item_features["feature_category_id"].unique()))

Category number :  73


In [12]:
item_features.head()

item_id  feature_category_id  feature_value_id
0        2                   56               365
1        2                   62               801
2        2                   68               351
3        2                   33               802
4        2                   72                75

In [6]:
candidate_items.head()

item_id
0        4
1        8
2        9
3       19
4       20

In [14]:
train_purchases[train_purchases["item_id"] == 15085]

session_id  item_id                     date
0                3    15085  2020-12-18 21:26:47.986
81109       362500    15085   2020-11-20 15:43:18.18
156247      695904    15085  2020-12-11 08:57:55.779
208983      931085    15085  2020-12-09 14:30:26.118
295572     1315209    15085  2020-12-17 21:23:08.308
302413     1344939    15085  2021-01-18 18:14:13.989
310688     1381862    15085  2020-12-11 22:39:54.123
350089     1556254    15085   2020-12-06 21:38:37.59
363762     1616554    15085  2020-11-29 12:24:28.595
395474     1757080    15085  2020-12-11 12:46:46.343
415525     1846229    15085  2020-11-29 23:36:47.915
425260     1889650    15085  2020-12-15 01:23:38.596
541205     2402569    15085  2020-11-18 20:48:54.404
572744     2541484    15085  2021-02-20 21:35:55.312
572977     2542686    15085  2021-01-01 11:16:40.674
596498     2649008    15085  2020-11-15 18:25:52.887
635008     2819205    15085  2021-01-21 22:15:51.399
635894     2823178    15085  2020-11-13 12:26:29.917
795729     3533543    15085   2020-12-04 08:44:34.31
822541     3652221    15085  2021-01-02 19:55:18.147
854527     3794265    15085  2021-01-21 15:43:36.313
919234     4081595    15085  2020-11-28 11:26:44.178
960642     4266147    15085  2020-12-05 15:20:22.146
961981     4272086    15085  2020-11-19 16:31:13.151
981924     4359676    15085  2020-12-14 16:58:49.528
996922     4426076    15085  2020-12-08 21:06:17.914

In [120]:
fulldf = train_purchases.copy()

In [121]:
def get_feature_string(history):
    res = ""
    for k,itm in enumerate(history):
        item = (item_features[item_features["item_id"] == itm]["feature_category_id"].astype("str") 
                + item_features[item_features["item_id"] == itm]["feature_value_id"].astype("str")).astype("str").str.cat(sep=" ")

        if k == 0:
            res += item
        else:
            res += " " + item
    return res
def get_features():
    return fulldf["session_id"].apply(lambda x: get_feature_string(train_sessions[train_sessions["session_id"] == x]["item_id"]))

In [ ]:
fulldf["features"] = get_features()

In [113]:
fulldf

session_id  item_id                     date  \
0              3    15085  2020-12-18 21:26:47.986   
1             13    18626  2020-03-13 19:36:15.507   
2             18    24911  2020-08-26 19:20:32.049   
3             19    12534   2020-11-02 17:16:45.92   
4             24    13226  2020-02-26 18:27:44.114   
...          ...      ...                      ...   
996         4542    18174  2020-09-03 11:31:03.968   
997         4543     4009  2021-05-31 10:46:47.018   
998         4546    12355  2020-08-15 18:10:34.777   
999         4554     1012   2020-04-27 06:08:15.37   
1000        4555    21253  2020-01-11 20:45:22.406   

                                               features  
0     56365 61898 36678 49465 31768 253 73544 55267 ...  
1     56365 47516 69780 68351 62801 53444 50708 6058...  
2     5689 19148 63861 32902 46825 45559 69709 26268...  
3     7452 50240 41145 46825 4736 56365 32902 3889 6...  
4     56365 4796 68502 61706 55129 30847 72655 12366...  
...                                                 ...  
996   56365 68739 7275 55267 50901 62801 63861 30478...  
997   69592 558 73544 3793 46825 68895 4618 65521 77...  
998   56365 8157 34275 25850 59180 47273 69639 30194...  
999   34275 47549 26507 56365 50901 72263 55152 7354...  
1000  34275 62801 50901 12410 46783 4796 30478 21353...  

[1001 rows x 4 columns]

In [67]:
cm = CountVectorizer().fit_transform(fulldf["features"])

In [68]:
cs = cosine_similarity(cm)
print(cs)

[[1.         0.05270463 0.14133305 ... 0.05407381 0.15891043 0.11785113]
 [0.05270463 1.         0.28492065 ... 0.10259784 0.39196475 0.372678  ]
 [0.14133305 0.28492065 1.         ... 0.22354067 0.51544084 0.38725804]
 ...
 [0.05407381 0.10259784 0.22354067 ... 1.         0.18560647 0.24853371]
 [0.15891043 0.39196475 0.51544084 ... 0.18560647 1.         0.59554321]
 [0.11785113 0.372678   0.38725804 ... 0.24853371 0.59554321 1.        ]]


In [87]:
def get_real_id_for_item(itm_id):
    return fulldf[fulldf["item_id"] == itm_id].values[0][0]

real_id = get_real_id_for_item(15085)

session_id  item_id                     date  \
401        1943    17186  2020-08-29 11:41:51.413   

                                              features  
401  56365 72557 17378 19545 41759 3793 32902 46825...

In [89]:
scores = list(enumerate(cs[real_id]))

In [90]:
sorted_scores = sorted(scores, key = lambda x: x[1], reverse=True)
sorted_scores = sorted_scores[1:]

In [101]:
print("TOP 5 >> Recommended item_id are : ")
for rec in sorted_scores[0:5]:
    print(fulldf[fulldf.index == rec[0]]["item_id"].values[0])

TOP 5 >> Recommended item_id are : 
17186
8861
20780
5858
8167
